### PR TITLE
Add CookieJar to NTLMTransport

### PR DESCRIPTION
**Pull request by codingLayce**
Hello,

First thanks for making this little tool that is really helping us on the NTLM Authentication.

I am making this pull request to add a cookieJar field in the NTLMTransport struct because i need to retrieve cookies sent during the NTLM Auth for a later use.

Thanks you in advance.

Lucas Guilbert.

### CODE REVIEW

**Comment by vadimi** [comment]
hello @codingLayce, thanks for your contribution. I have a few questions on the change. Technically NTLM auth does not require cookies, but if your original `req` has cookies they will get sent after the successful auth request. Do you have some sort of custom NTLM auth that requires cookies?

**Comment by codingLayce** [comment]
Hello, it's not my `req` that has cookies but the service i am authenticating on is sending me a SMSESSION cookie on success that i need for further authentication. Thanks you for your time.

**Comment by vadimi** [comment]
ah, SiteMinder, I remember that one :) Merging your PR.

**Comment by codingLayce** [comment]
Perfect thanks you !

**Pull request merged**
